name: Django CI

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .
    - name: Run Tests
      run: |
        coverage run -m pytest
        coverage report
      working-directory: .
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Install Cypress
      run: |
        npm install cypress
      working-directory: .
    - name: Run Cypress Tests
      run: |
        python manage.py runserver
        npx cypress run
      working-directory: .
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}